export const SIGNIN_ACTION_REQUEST= "SIGNIN_ACTION_REQUEST";
export const SIGNIN_ACTION_SUCCESS= "SIGNIN_ACTION_SUCCESS";
export const SIGNIN_ACTION_FAIL= "SIGNIN_ACTION_FAIL";

export const SIGNUP_ACTION_REQUEST= "SIGNUP_ACTION_REQUEST";
export const SIGNUP_ACTION_SUCCESS= "SIGNUP_ACTION_SUCCESS";
export const SIGNUP_ACTION_FAIL= "SIGNUP_ACTION_FAIL";

export const SIGNOUT_ACTION_REQUEST= "SIGNOUT_ACTION_REQUEST";
export const SET_MODAL = 'SET_MODAL';
export const SET_TODOS = 'SET_TODOS';
export const SET_LOADING = 'SET_LOADING';
export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_SELECTED_TAG = 'SET_SELECTED_TAG';
export const SET_SELECTED_COMPLETION = 'SET_SELECTED_COMPLETION';
export const TOGGLE_TODOS = 'TOGGLE_TODOS';
export const UPDATE_TODOS = 'UPDATE_TODOS';
export const DELETE_TODOS = 'DELETE_TODOS';
export const SETUP_DASHBOARD = 'SETUP_DASHBOARD';